### ISSUE TITLE
Updating server

### ISSUE THREAD

**Issue by Kabouik** [fakundo/valheim-server#2]
Hi, and thanks for this repository. 

Could you please elaborate on whether this docker image allows auto-updates of the server when no players are connected? Alternatively, how should one proceed to manually update the server from command line using this setup?

Thanks in advance.

[Edit] What I did to update the server manually was:
1. Go to the web interface to stop the server.
2. `ssh` into my machine.
3. `docker exec -it <ContainerID> /bin/bash` to run commands from inside the container. If the container is not running, _i.e._, after a reboot of the machine, start it first using `docker start valheim_valheim_1`.
4. From bash in the container, run `/root/.steam/steamcmd/./steamcmd.sh +login anonymous +force_install_dir /root/valheim +app_update 896660 validate +exit`.
5. Restart the server from the web interface.

**Comment by fakundo** [comment]
Hey! Thanks for your feedback!
Right now I'm not planning to make server auto-update.
Perhaps I will do this in the future when I make some improvements, such as analysing the server process output to get the number of online players.
To update the server manually, you just need to Stop / Start it with the web interface. When you press Start, this command will be executed.
```
err = v.exec(
env.SteamCmdPath,
"+login", "anonymous",
"+force_install_dir", env.ValheimPath,
"+app_update", "896660",
"+quit")
```

**Comment by Kabouik** [comment]
Oh, so this is already pretty close to auto-updating, the admin just has to manually stop and restart. I didn't know that. Sounds like a good balance, perhaps safer than true auto-updates.

I haven't used my VH server lately but I sure will try that next time, instead of manually running the command as I did above (which probably was not necessary since restarting from the web UI would have done the same).
